import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MatListModule, MatDialogModule, MatChipsModule, MatTooltipModule, MatDividerModule, MatIconModule, MatTreeModule,
   MatMenuModule, MatTabsModule, MatButtonModule, MatRadioModule, MatFormFieldModule, MatInputModule, MatProgressSpinnerModule, MatSnackBarModule,
    MatSelectModule, MatSlideToggleModule, MatToolbarModule, MatGridListModule, MatCardModule, MatSidenavModule, MatRippleModule, MatPaginator,
     MatPaginatorModule, MatDatepickerModule, MatCheckboxModule, MatOptionModule, MatNativeDateModule, MatBadgeModule,MatStepperModule, MatTableDataSource, MatTableModule } from '@angular/material';


import { LayoutModule } from '@angular/cdk/layout';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { FormsModule } from '@angular/forms';
import { MatMomentDateModule } from "@angular/material-moment-adapter";
import { CommonModule } from '@angular/common';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    RouterModule,
    MatListModule,
    MatDialogModule,
    MatChipsModule,
    MatTooltipModule,
    MatDividerModule,
    MatIconModule,
    MatTreeModule,
    MatMenuModule,
    MatTabsModule,
    MatButtonModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatCheckboxModule,
    MatOptionModule,
    MatNativeDateModule,
    MatOptionModule,
    MatPaginatorModule,
    LayoutModule,
    MatRadioModule,
    MatFormFieldModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatToolbarModule,
    MatGridListModule,
    MatCardModule,
    MatSidenavModule,
    MatRippleModule,
    MatBadgeModule,
    MatStepperModule,
    // MatTableDataSource,
    MatTableModule,
    // BrowserAnimationsModule,
    ScrollingModule,
    FormsModule,
  ] ,
  exports:[
    RouterModule,
    MatListModule,
    MatDialogModule,
    MatChipsModule,
    MatTooltipModule,
    MatDividerModule,
    MatIconModule,
    MatTreeModule,
    MatMenuModule,
    MatTabsModule,
    MatDatepickerModule,
    MatMomentDateModule,
    MatCheckboxModule,
    MatOptionModule,
    MatNativeDateModule,
    MatOptionModule,
    MatButtonModule,
    MatPaginatorModule,
    LayoutModule,
    MatRadioModule,
    MatFormFieldModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatToolbarModule,
    MatGridListModule,
    MatCardModule,
    MatSidenavModule,
    MatRippleModule,
    MatBadgeModule,
    MatStepperModule,
    MatTableModule,
    // BrowserAnimationsModule,
    CommonModule,
    ScrollingModule,
    FormsModule,
  ]
})
export class MaterialModule { }
